# Generated by Django 3.1 on 2023-02-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_material_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
